triggers:
  get:
    summary: "get all triggers"
    operationId: GetTriggers
    tags:
      - trigger
    responses:
      $ref: ./responses.yml#/get_triggers

  put:
    summary: "create new trigger"
    operationId: CreateTrigger
    tags:
      - trigger
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: ./requests.yml#/create_trigger
    responses:
      $ref: ./responses.yml#/create_trigger

trigger:
  put:
    summary: "Update existing trigger"
    operationId: UpdateTrigger
    tags:
      - trigger
    parameters:
      - $ref: ../shared/parameters/_index.yml#/triggerID
    requestBody:
      required: true
      content:
        application/json:
          schema:
            $ref: "../shared/schemas/Trigger.yml#/Trigger"
    responses:
      $ref: responses.yml#/put
  get:
    summary: "Get an existing trigger"
    operationId: GetTrigger
    tags:
      - trigger
    parameters:
      - $ref: ../shared/parameters/_index.yml#/triggerID
    responses:
      $ref: ./responses.yml#/get

render:
  get:
    summary: "Get rendered plot for trigger"
    operationId: GetTriggerPlot
    tags:
      - trigger
    parameters:
      - $ref: ../shared/parameters/_index.yml#/triggerID
      - $ref: ../shared/parameters/_index.yml#/targetID
      - $ref: ../shared/parameters/_index.yml#/from
      - $ref: ../shared/parameters/_index.yml#/to
    responses:
      $ref: ./responses.yml#/get_render

metrics:
  get:
    summary: "Get metrics associated with certain trigger"
    operationId: GetTriggerMetrics
    tags:
      - trigger
    parameters:
      - $ref: ../shared/parameters/_index.yml#/triggerID
      - $ref: ../shared/parameters/_index.yml#/from
      - $ref: ../shared/parameters/_index.yml#/to
    responses:
      $ref: ./responses.yml#/get_metrics

page:
  get:
    summary: "Search triggers. Deprecated, use the `search` endpoint instead"
    deprecated: true
    operationId: SearchTriggersPage
    tags:
      - trigger
    parameters:
      - $ref: ../shared/parameters/_index.yml#/onlyProblems
      - $ref: ../shared/parameters/_index.yml#/page
      - $ref: ../shared/parameters/_index.yml#/text
    responses:
      $ref: ./responses.yml#/page_triggers

search:
  get:
    summary: "Search triggers. Replaces the deprecated `page` path"
    operationId: SearchTriggers
    tags:
      - trigger
    parameters:
      - $ref: ../shared/parameters/_index.yml#/onlyProblems
      - $ref: ../shared/parameters/_index.yml#/page
      - $ref: ../shared/parameters/_index.yml#/text
    responses:
      $ref: ./responses.yml#/search_triggers

state:
  get:
    summary: "Get the trigger state as at last check"
    operationId: GetTriggerState
    tags:
      - trigger
    parameters:
      - $ref: ../shared/parameters/_index.yml#/triggerID
    responses:
      $ref: ./responses.yml#/state/get
