triggers:
  get_triggers:
    200:
      description: "fetched all triggers"
      content:
        application/json:
          schema:
            type: object
            properties:
              list:
                type: array
                description: "list of available triggers"
                items:
                  $ref: "../shared/schemas/Trigger.yml#/Trigger"

  create_trigger:
    200:
      description: "Trigger created"
      content:
        application/json:
          schema:
            type: object
            properties:
              id:
                type: string
                example: trigger_id
              message:
                type: string
                example: trigger created
    400:
      description: "Failed to create trigger due to invalid request body"
      content:
        application/json:
          schema:
            $ref: "../shared/schemas/Errors.yml#/ErrorBadRequest"
          examples:
            targetRequired:
              description: "no value passed for 'target' field"
              value:
                status: "Invalid request"
                error: "targets is required"

get_render:
  200:
    description: "Plot for trigger"
    content:
      image/png:
        schema:
          type: string
          format: binary
  500:
    $ref: "../shared/responses/_index.yml#/ServerError"

trigger:
  delete:
    200:
      description: "Trigger has been deleted"
    400:
      description: "Trigger not found"
      content:
        application/json:
          schema:
            $ref: "../shared/schemas/Errors.yml#/ErrorBadRequest"
          examples:
            triggerNotFound:
              description: "no trigger with the ID was found"
              value:
                status: "Invalid request"
                error: "trigger not found"

  put:
    200:
      description: "Trigger updated"
      content:
        application/json:
          schema:
            type: object
            properties:
              id:
                type: string
                example: trigger_id
              message:
                type: string
                example: trigger created
    400:
      $ref: "../shared/responses/_index.yml#/BadRequest"

  get:
    200:
      description: "Trigger data"
      content:
        application/json:
          schema:
            $ref: "../shared/schemas/Trigger.yml#/Trigger"
    404:
      $ref: "../shared/responses/_index.yml#/NotFound"



metrics:
  delete_metric:
    200:
      description: "Trigger metric has been deleted"
    400:
      description: "Trigger not found"
      content:
        application/json:
          schema:
            $ref: "../shared/schemas/Errors.yml#/ErrorBadRequest"
          examples:
            triggerNotFound:
              description: "no trigger with the ID was found"
              value:
                status: "Invalid request"
                error: "trigger not found"

  get_metrics:
    200:
      description: "Metrics for trigger"
      content:
        application/json:
          schema:
            type: object
            additionalProperties:
              type: array
              items:
                $ref: "../shared/schemas/MetricValue.yml#/MetricValue"
    400:
      description: "Trigger not found"
      content:
        application/json:
          schema:
            $ref: "../shared/schemas/Errors.yml#/ErrorBadRequest"
          examples:
            triggerNotFound:
              description: "no trigger with the ID was found"
              value:
                status: "Invalid request"
                error: "trigger not found"
    500:
      $ref: "../shared/responses/_index.yml#/ServerError"

metrics_nodata:
   delete:
     200:
       description: "NODATA metrics have been deleted"

page_triggers:
  200:
    description: "fetched matching triggers"
    content:
      application/json:
        schema:
          type: object
          properties:
            page:
              type: number
              description: "current item page"
              example: 0
            size:
              type: number
              description: "number of triggers shown per page"
              example: 10
            total:
              type: number
              description: "total number of matching results"
              example: 5
            list:
              type: array
              description: "list of matching triggers"
              items:
                $ref: "../shared/schemas/Trigger.yml#/Trigger"

search_triggers:
  200:
    description: "fetched matching triggers"
    content:
      application/json:
        schema:
          type: object
          properties:
            page:
              type: number
              description: "current item page"
              example: 0
            size:
              type: number
              description: "number of triggers shown per page"
              example: 10
            total:
              type: number
              description: "total number of matching results"
              example: 5
            list:
              type: array
              description: "list of matching triggers"
              items:
                $ref: "../shared/schemas/Trigger.yml#/Trigger"

state:
  get:
    200:
      description: "trigger state fetched successfully"
      content:
        application/json:
          schema:
            $ref: "../shared/schemas/TriggerCheck.yml#/TriggerCheck"

setMaintenance:
  put:
    200:
      description: "trigger or metric have been scheduled for maintenance"
    400:
      $ref: "../shared/responses/_index.yml#/BadRequest"

throttling:
  get:
    200:
      description: "trigger throttle info retrieved"
      content:
        application/json:
          schema:
            type: object
            properties:
              throttling:
                type: integer
                description: "unix timestamp to show next allowed time, defaults to 0"
                example: 0
    404:
      $ref: "../shared/responses/_index.yml#/NotFound"

  delete:
    200:
      description: "trigger throttling has been deleted"
    404:
      $ref: "../shared/responses/_index.yml#/NotFound"
