# coding: utf-8

"""
    Moira Alert

    This is an API description for [Moira Alert project](https://moira.readthedocs.io/en/latest/overview.html). Please check <https://github.com/moira-alert/>  # noqa: E501

    The version of the OpenAPI document: 2.5.1.48
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest

import openapi_client
from openapi_client.api.trigger_api import TriggerApi  # noqa: E501
from openapi_client.rest import ApiException


class TestTriggerApi(unittest.TestCase):
    """TriggerApi unit test stubs"""

    def setUp(self):
        self.api = openapi_client.api.trigger_api.TriggerApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_create_trigger(self):
        """Test case for create_trigger

        create new trigger  # noqa: E501
        """
        pass

    def test_delete_trigger(self):
        """Test case for delete_trigger

        remove a trigger  # noqa: E501
        """
        pass

    def test_delete_trigger_metric(self):
        """Test case for delete_trigger_metric

        deletes metric from last check and all trigger pattern metrics  # noqa: E501
        """
        pass

    def test_delete_trigger_no_data_metrics(self):
        """Test case for delete_trigger_no_data_metrics

        deletes all metrics from last data which are in NODATA state. It also deletes all trigger patterns of those metrics  # noqa: E501
        """
        pass

    def test_delete_trigger_throttling(self):
        """Test case for delete_trigger_throttling

        Deletes throttling for a trigger  # noqa: E501
        """
        pass

    def test_get_trigger(self):
        """Test case for get_trigger

        Get an existing trigger  # noqa: E501
        """
        pass

    def test_get_trigger_metrics(self):
        """Test case for get_trigger_metrics

        Get metrics associated with certain trigger  # noqa: E501
        """
        pass

    def test_get_trigger_plot(self):
        """Test case for get_trigger_plot

        Get rendered plot for trigger  # noqa: E501
        """
        pass

    def test_get_trigger_state(self):
        """Test case for get_trigger_state

        Get the trigger state as at last check  # noqa: E501
        """
        pass

    def test_get_trigger_throttling(self):
        """Test case for get_trigger_throttling

        Get a trigger with its throttling i.e its next allowed message time  # noqa: E501
        """
        pass

    def test_get_triggers(self):
        """Test case for get_triggers

        get all triggers  # noqa: E501
        """
        pass

    def test_search_triggers(self):
        """Test case for search_triggers

        Search triggers. Replaces the deprecated `page` path  # noqa: E501
        """
        pass

    def test_search_triggers_page(self):
        """Test case for search_triggers_page

        Search triggers. Deprecated, use the `search` endpoint instead  # noqa: E501
        """
        pass

    def test_set_trigger_maintenance(self):
        """Test case for set_trigger_maintenance

        sets metrics and the trigger itself to maintenance mode  # noqa: E501
        """
        pass

    def test_update_trigger(self):
        """Test case for update_trigger

        Update existing trigger  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
